name: Laravel CI/CD

on:
  push:
    branches: [ "master" ]  # Laravel 10 ใช้ branch master เป็นค่าเริ่มต้น
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: artbid_lgv1
          POSTGRES_USER: artbid
          POSTGRES_PASSWORD: T73IK4XOW0oIIrjdYKCEUaXh4jUSjci2
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U artbid -d artbid_lgv1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4  # อัปเดตเป็นเวอร์ชันล่าสุด

      - name: Setup Node.js (จำเป็นสำหรับ Laravel 10)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, bcmath, curl, pgsql, pdo_pgsql, ctype, fileinfo, openssl, tokenizer
          coverage: none
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Copy .env
        run: cp .env.example .env

      - name: Configure .env for PostgreSQL
        run: |
          echo "APP_ENV=production" >> .env
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=T73IK4XOW0oIIrjdYKCEUaXh4jUSjci2.singapore-postgres.render.com" >> .env  # เปลี่ยนจาก 127.0.0.1 เป็นชื่อ service
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=artbid_lgv1" >> .env
          echo "DB_USERNAME=artbid" >> .env
          echo "DB_PASSWORD=T73IK4XOW0oIIrjdYKCEUaXh4jUSjci2" >> .env
          echo "APP_KEY=" >> .env

      - name: Generate application key
        run: php artisan key:generate --force

      - name: Run migrations and seed
        run: php artisan migrate:fresh --seed --force

      - name: Run tests
        run: php artisan test

      - name: Upload artifact (สำหรับการ deploy)
        uses: actions/upload-artifact@v3
        with:
          name: laravel-artifact
          path: |
            .
            !vendor/
            !node_modules/

  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # เปลี่ยนจาก master เป็น master
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: laravel-artifact

      - name: Trigger Render Deployment
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"