name: Laravel CI/CD to Render

on:
  push:
    branches: [ "master" ]  # เปลี่ยนตาม branch ที่คุณใช้ deploy จริง

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: artbid_lgv1
          POSTGRES_USER: artbid
          POSTGRES_PASSWORD: T73IK4XOW0oIIrjdYKCEUaXh4jUSjci2
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U artbid -d artbid_lgv1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (Laravel asset build)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, bcmath, curl, pgsql, pdo_pgsql, ctype, fileinfo, openssl, tokenizer
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Copy .env
        run: cp .env.example .env

      - name: Setup Laravel env for test
        run: |
          echo "APP_ENV=testing" >> .env
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=artbid_lgv1" >> .env
          echo "DB_USERNAME=artbid" >> .env
          echo "DB_PASSWORD=T73IK4XOW0oIIrjdYKCEUaXh4jUSjci2" >> .env
          echo "APP_KEY=" >> .env

      - name: Generate app key
        run: php artisan key:generate --force

      - name: Run migration and seeder
        run: php artisan migrate:fresh --seed --force

      - name: Run Laravel tests
        run: php artisan test

  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # deploy เฉพาะเมื่อ push ไปที่ master
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
